#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ ( "$SHLVL" -eq 1 && ! -o LOGIN ) && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

#llvm
#export PATH=/usr/local/Cellar/llvm/15.0.6/bin:$PATH
#PATH="/usr/local/opt/llvm/bin:$PATH"

# java home directory
export JAVA_HOME=$(/usr/libexec/java_home)

export PYENV_ROOT="$HOME/.pyenv"
export PIPENV_PYTHON="$PYENV_ROOT/shims/python"

export GCLOUD_DIR="$HOME/google-cloud-sdk/bin"
